const career=new URLSearchParams(location.search).get("career")||"Your target career";document.getElementById("title").textContent=`Roadmap: ${career}`;const skills={"AI / ML Engineer": "Python, ML, statistics", "Data Scientist": "Python, SQL, statistics", "Data Analyst": "SQL, Excel, dashboards", "Data Engineer": "SQL, Python, pipelines", "Machine Learning Engineer": "Python, ML, deployment", "AI Product Manager": "Strategy, AI, communication", "Product Manager": "Strategy, research, communication", "Product Designer": "UX, research, prototyping", "UX Researcher": "Research, interviews, synthesis", "UI Designer": "Visual design, Figma, systems", "UX Engineer": "HTML, CSS, JavaScript, UX", "Frontend Developer": "HTML, CSS, JavaScript", "Backend Developer": "APIs, databases, programming", "Full Stack Developer": "Frontend, backend, databases", "Mobile App Developer": "Android/iOS, APIs, UI", "DevOps Engineer": "Linux, CI/CD, automation", "Cloud Engineer": "Cloud platforms, networking, Linux", "Site Reliability Engineer": "Linux, observability, automation", "Cloud Security Engineer": "Cloud, IAM, security", "Cybersecurity Analyst": "Networks, security, risk", "Security Engineer": "AppSec, networks, threat modeling", "Penetration Tester": "Web security, networks, testing", "Security Operations Analyst": "SIEM, incident response", "Network Engineer": "TCP/IP, routing, switching", "Systems Administrator": "Linux/Windows, networking", "Database Administrator": "SQL, databases, backup", "QA Engineer": "Testing, automation, debugging", "Automation Engineer": "Python, scripting, workflows", "Game Developer": "Game engines, programming, 3D", "AR/VR Developer": "3D, Unity/Unreal, interaction", "Blockchain Developer": "Smart contracts, cryptography", "Embedded Systems Engineer": "C/C++, microcontrollers", "Robotics Engineer": "Control, Python/C++, robotics", "Electronics Engineer": "Circuits, embedded systems", "Technical Writer": "Documentation, research, clarity", "Content Strategist": "Writing, research, analytics", "Digital Marketing Specialist": "SEO, analytics, campaigns", "Business Analyst": "Analysis, requirements, communication", "Financial Analyst": "Excel, financial modeling, analysis", "Management Consultant": "Problem solving, research, communication", "Recruiter / Talent Partner": "Sourcing, interviewing, communication"};
const skill=skills[career]||"Core skills, projects, communication";
const steps=[["01","FOUNDATION",`Understand the role and build your base in ${skill}.`],["02","BUILD",`Create 2–3 practical ${career} projects. Document the problem, approach, tools and outcome.`],["03","SIGNAL",`Turn your projects into portfolio evidence, concise resume bullets and a clear explanation of what you can do.`],["04","MOVE",`Practice role-specific interviews, apply deliberately, collect feedback and update this roadmap as you progress.`]];
document.getElementById("timeline").innerHTML=steps.map((s,i)=>`<article class="road-row"><span class="road-dot"></span><div class="panel road-card"><div><span class="tag">${s[0]}</span><h3>${s[1]}</h3><p class="muted">${s[2]}</p></div><div class="bar"><i style="--value:${(i+1)*25}%"></i></div></div></article>`).join("");
const progressKey=`nexora_progress_${career}`;
let progress=Number(localStorage.getItem(progressKey)||0);
const fill=document.getElementById('progressFill'), label=document.getElementById('progressLabel'), mark=document.getElementById('markProgress');
function paintProgress(){if(fill)fill.style.width=progress+'%';if(label)label.textContent=progress+'% complete';if(mark)mark.textContent=progress>=100?'Roadmap complete ✓':'Mark next stage ✓'}
mark?.addEventListener('click',()=>{progress=Math.min(100,progress+25);localStorage.setItem(progressKey,progress);paintProgress();});paintProgress();
